apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/app"

        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/app" -}}
          USERNAME={{ .Data.data.username }}
          PASSWORD={{ .Data.data.password }}
          {{- end }}

    spec:
      serviceAccountName: default

      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000

          # Secrets
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}-secret

            # ConfigMap ENV
            - configMapRef:
                name: {{ include "app.fullname" . }}-env

          # env
          env:
            - name: ENV
              value: "production"

          # Volume mounts
          volumeMounts:
            # ConfigMap
            - name: config-volume
              mountPath: /config

            # PVC
            - name: data-volume
              mountPath: /data

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

      # Volumes
      volumes:
        # ConfigMap file
        - name: config-volume
          configMap:
            name: {{ include "app.fullname" . }}-config

        # Persistent Volume
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc